---
title: "'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 7e7d1a1a9025c2d708d7e5027fd9bcbb4270e60b
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62027465"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir
`Exit Try` yalnızca içinde görünebilir bir `Try` deyimi engelleyin. Ya da bir yedek sahip `Exit Try` deyimi veya `Exit Try` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30393  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Bulmak ve gereksiz kaldırma `Exit Try` deyimi.  
  
2. Taşıma `Exit Try` kodunuz içinde uygun konuma deyimi.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
