---
title: "'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 53c8ee60907db16ac97147100636e413f1cbc15e
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58043362"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir
`Exit Try` yalnızca içinde görünebilir bir `Try` deyimi engelleyin. Ya da bir yedek sahip `Exit Try` deyimi veya `Exit Try` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30393  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Bulmak ve gereksiz kaldırma `Exit Try` deyimi.  
  
2.  Taşıma `Exit Try` kodunuz içinde uygun konuma deyimi.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
