---
title: "'Finally' dışında bir 'Try' deyimi yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 210f4cc25ba47d89839c65dc91042d884635d5db
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58028891"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>'Finally' dışında bir 'Try' deyimi yer alamaz
`Finally` tamamlamak için kullanılan bir `Try...Catch...Finally` engelle; Bu nedenle yalnızca bir kez bloğun sonunda görünebilir. Ya da gereksiz bir sahip `Finally`, veya `Finally` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30382  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Bulmak ve gereksiz kaldırma `Finally` deyimi.  
  
2.  Taşıma `Finally` kodunuzdaki uygun konuma deyimi.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
