---
title: Derleyici Hatası CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: d1e9e93e78b493810512bc9f94a9a0d9e4db8e91
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 08/19/2019
ms.locfileid: "69604029"
---
# <a name="compiler-error-cs0103"></a>Derleyici Hatası CS0103
' Tanımlayıcı ' adı geçerli bağlamda yok  
  
 Sınıf, [ad alanı](../keywords/namespace.md)veya kapsamda bulunmayan bir adı kullanma girişiminde bulunuldu. Kullanmaya çalıştığınız adın kullanılabilir olduğundan emin olmak için adın yazımını denetleyin ve kullandığınız yönergeleri ve derleme başvurularını denetleyin.  
  
 Bu hata, bir döngü veya bir `try` ya da `if` blok içinde bir değişken bildirirseniz ve ardından bunu kapsayan bir kod bloğundan veya ayrı bir kod bloğundan erişmeyi denerseniz, aşağıdaki örnekte gösterildiği gibi sıklıkla oluşur.  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 Aşağıdaki örnek hatayı çözer.  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```
