---
title: Derleyici Hatası CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: 7bf3e71d9616baca5efb86983e82450fc1d01d88
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61672061"
---
# <a name="compiler-error-cs0103"></a>Derleyici Hatası CS0103
'İdentifier' adı geçerli bağlamda yok  
  
 Sınıfında mevcut olmayan bir ad kullanmak için bir girişimde bulunuldu [ad alanı](../../../csharp/language-reference/keywords/namespace.md), veya kapsam. Adının yazımını denetleyin ve kullanarak kontrol yönergeleri ve derleme başvurularını kullanmayı denemekte olduğunuz adı kullanılabilir olduğundan emin olun.  
  
 Döngü içinde bir değişken bildirirseniz bu hata sık oluşur veya `try` veya `if` engellemek ve ardından kapsayan bir kod bloğu ya da ayrı bir kod bloğu erişmek aşağıdaki örnekte gösterildiği gibi çalışır.  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 Aşağıdaki örnek, hatanın çözümler.  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```
